version: '3.7'

services:
  db:
    container_name: postgres_finance_app
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - '5433'
    ports:
      - '5434:5434'
    command: -p 5434

  redis:
    container_name: redis_finance_app
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    restart: always